# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
# https://rancher.com/docs/rancher/v2.5/en/k8s-in-rancher/horitzontal-pod-autoscaler/testing-hpa/
# https://docs.oracle.com/pt-br/iaas/Content/ContEng/Tasks/contengusinghorizontalpodautoscaler.htm
apiVersion: autoscaling/v2
#apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-clientes
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 5
  maxReplicas: 25
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 15
