# Vertical Pod Autoscaler para o MongoDB
apiVersion: autoscaling/v2
kind: VerticalPodAutoscaler
metadata:
  name: mongo-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       StatefulSet
    name:       mongo
  updatePolicy:
    updateMode: "Auto"
