kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-10a4481b-b000-4950-8039-38489bf835f2
  namespace: portworx
  annotations:
    portworx.io/install-source: "https://install.portworx.com/3.2?operator=true&mc=false&kbver=1.31.7&ns=portworx&b=true&iop=6&s=%22type%3DPremium_LRS%2Csize%3D32%22&ce=azure&c=px-cluster-10a4481b-b000-4950-8039-38489bf835f2&aks=true&stork=true&csi=true&mon=true&tel=true&st=k8s&promop=true"
    portworx.io/is-aks: "true"
spec:
  image: portworx/oci-monitor:3.2.3
  imagePullPolicy: Always
  kvdb:
    internal: true
  cloudStorage:
    deviceSpecs:
      - type=Premium_LRS,size=32
    maxStorageNodesPerZone: 2
    minStorageNodes: 2
    storageNodesPerZone: 2
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  runtimeOptions:
    default-io-profile: "6"
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      enabled: true
      exportMetrics: true
  env:
    - name: AZURE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: px-azure
          key: AZURE_CLIENT_ID
    - name: AZURE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: px-azure
          key: AZURE_CLIENT_SECRET
    - name: AZURE_TENANT_ID
      valueFrom:
        secretKeyRef:
          name: px-azure
          key: AZURE_TENANT_ID
    - name: PX_ALLOW_SHARED_DEVICE_ACCESS
      value: "1"
    - name: PX_ENABLE_DU_MODE
      value: "true"
    - name: PX_NUM_STORAGE_NODES
      value: "2"
