# https://hub.docker.com/r/microsoft/windows-cssc-python
FROM mcr.microsoft.com/windows-cssc/python:3.11-servercore-ltsc2022

WORKDIR /app

COPY . .
RUN pip install -r requirements.txt

EXPOSE 5000
CMD ["python", "app_win.py"]
