apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-access-permitir
  namespace: namespace-a
spec:
  podSelector: {}  # Aplica a todos os pods em namespace-a
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}  # Qualquer namespace
          podSelector:
            matchLabels:
              acesso: permitir
