apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-fiap-app-config
spec:
  endpoint: ${APPCONFIG_URL}
  target:
    configMapName: app-config-map
  configuration:             # <--- Campo principal para configuração de chaves-valores
    selectors:
      - keyFilter: "*"       # Pega todas as chaves
        labelFilter: ""      # Especifique um label se necessário, ou use "\0" para nenhum label
    refresh:                 # <--- Configurações de refresh para as chaves selecionadas acima
      enabled: true
      interval: "5s"       # Intervalo de atualização (precisa ser uma string de duração, ex: "30s", "1m", "2h30m")
