apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-fiap-app-config
spec:
  endpoint: ${APPCONFIG_URL}
  target:
    configMapName: ${NOME_APP_CONFIG}
