apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-fiap-app-config
spec:
  endpoint: ${APPCONFIG_URL}
  target:
    configMapName: app-config-map
  keyValues:
    # Seleciona as chaves que você quer monitorar
    - keyFilter: "*" # Pega todas as chaves.
      labelFilter: "" # Adicione um filtro de label se usar labels no App Configuration
      # Configuração de Refresh
      refresh:
        enabled: true
        interval: 5s # Define um intervalo para verificar por mudanças.
