trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  helmVersion: '3.12.0'

steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: '$(helmVersion)'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'conexao-azure'
    azureResourceGroup: 'fiap-rg'
    kubernetesCluster: 'fiap-aks'
    namespace: 'default'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'charts/fiap-chart'
    releaseName: 'fiap-release'
    overrideValues: |
      image.repository=tonanuvem/page
