apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-env-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app-env
  template:
    metadata:
      labels:
        app: python-app-env
    spec:
      containers:
      - name: python-app-env
        image: tonanuvem/python-app-env:linux
        imagePullPolicy: Always
        env:
        - name: chave1 # Do ConfigMap
          valueFrom:
            configMapKeyRef:
              name: app-config-map
              key: chave1
        - name: chave2 # Do ConfigMap
          valueFrom:
            configMapKeyRef:
              name: app-config-map
              key: chave2
        # Nova variável de ambiente vinda do Secret
        - name: SEGREDO_DO_APP # Nome da variável de ambiente no seu pod
          valueFrom:
            secretKeyRef:
              name: app-secret      # Nome do Secret Kubernetes
              key: segredo1         # Chave dentro do Secret (deve corresponder ao nome da chave no App Configuration para a referência do KV)
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-env-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: python-app-env
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
