apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-rolebinding-read
  namespace: default
subjects:
- kind: User
  name: aluno@fiap.com.br # Substitua pelo email correto
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-pod-read
  apiGroup: rbac.authorization.k8s.io
