apiVersion: v1
kind: Service
metadata:
  name: python-env-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: python-env-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
