admin:
  user: fiap
  password: fiap

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server
        isDefault: true

service:
  type: ClusterIP
  port: 80

grafana.ini:
  server:
    root_url: "http://${HOST_GRAFANA}:8099/proxy/3000/"
    serve_from_sub_path: true
