name: Build and Push Windows Docker Image to Docker Hub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker image (Windows)
      run: |
        docker build -t tonanuvem/python-app-env:win -t tonanuvem/python-app-env:${{ github.run_id }} -f ./helmcharts/python-app-env/Dockerfile.win ./helmcharts/python-app-env

    - name: Push Docker image to Docker Hub
      run: |
        docker push tonanuvem/python-app-env:win
        # docker push tonanuvem/python-app-env:${{ github.run_id }}
